import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "./_partials/Header";
import Footer from "./_partials/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "TodoList",
  description: "Generated by raya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
